# 例外処理
プログラムがエラーで異常終了するケースでもプログラムを中断させず、別の処理に切り替えるプログラムのこと。    

## ❓ 例外処理がなぜ必要??
普通にエラーを返せば良くない??
~~~
例外処理っていうのは、プログラムが予想外のことに遭遇した時に、上手く対応できるようにするための仕組みだよ。

例えば、君がゲームをしていて、急に画面がフリーズしたら嫌だよね？
でも例外処理があれば、フリーズする代わりに「ごめんね、何か問題が起きたよ。もう一度やってみよう！」ってメッセージを表示できるんだ。
これでゲームがいきなり止まることなく、もう一度チャレンジできるね。

エラーをそのまま返すだけだと、人が使っているときに困ったり、何が悪いのかわからなくなったりすることがあるから、
例外処理をしっかり作ると、使っている人が困らないようにできるんだよ。
~~~
***

# 「begin、rescue、end」の基本構文
~~~
begin
例外が起こるかも知れない処理
rescue　例外クラス　<= StandardErrorの時は
例外が発生した時の処理
end
~~~
***

# ⭐️ rescue
- rescue エラークラス指定 ⇒ e    
指定されたクラスの下の階層にある例外だけを補足する。      
        
- rescue ⇒ e    
デフォルトでStandardErrorクラスを指定する。    
***

## 例:割り勘プログラムで０人で割ろうとするとエラーが出る。
~~~
puts "金額を入力してください。"
bill = gets.to_i
puts "割り勘人数を入れてください。"
num = gets.to_i

warikan = bill / num
puts "一人当たり#{warikan}です。"

# num = 0 の実行結果
rb:6:in `/': divided by 0 (ZeroDivisionError)
	from chap111.rb:6:in `<main>'
~~~
    
これを    
    
~~~
puts "金額を入力してください。"
bill = gets.to_i
puts "割り勘人数を入れてください。"
num = gets.to_i

begin #エラーが出るかもしれない処理
	warikan = bill / num
	puts "一人当たり#{warikan}です。"
rescue ZeroDivisionError => e　　#例外が発生したら行う処理
# ZeroDivisionErrorが出たら表示する。
	puts "おっと、０人では割り勘できません！: #{e.class}"
end

# num = 0 の実行結果
おっと、０人では割り勘できません！: ZeroDivisionError
~~~
こうなる。
***

# ⭐️ raise
例外を発生させる。	

⭐️ raiseが実行されると、それに対応する rescueも実行されることが多い。
~~~
raise "例外メッセージ"
~~~
    
- raise “例外メッセージ”    
デフォルトでRuntimeErrorクラスが発生される。    
    
- raise 例外クラス ”例外メッセージ”    
指定されたクラスを発生させられる。

## ❓ raiseはなぜ必要?? rescueだけではだめ??
~~~
例外をわざわざ発生させるのは、プログラムをもっと賢くするためだよ。

例えば、君が交通整理のおまわりさんだとして、道に大きな穴があいてるのを見つけたとするね。
そのまま何もしないで車を通すと、車は穴に落ちてしまう。これがエラーが出た状態だね。
でも、おまわりさんが「ここに大きな穴があるよ！」ってみんなに教えてあげる（=例外を発生させる）と、車は別の安全な道を通ることができる。
つまり、例外を発生させるっていうのは、プログラムが危険を知らせて、もっと良い方法で問題を解決しようとしているんだね。

rescueだけだと、エラーが起きたときの応急処置みたいなもので、なぜそのエラーが起きたのか、どうやってうまく避けるかは考えない。
raiseを使うと、エラーがどこでどうして起きるのかをもっと理解して、同じ問題が起きないように先手を打てるんだよ。
~~~
***

## 例: 年齢で成年、未成年を判定するメソッド
~~~
def type(age)
	begin
		if age < 0
			raise "年齢がマイナスです！"
		elsif age < 20
			"未成年"
		else
			"成年"
		end
	end
end

type = type(-5)
puts "#{age}歳は#{type}です。"

# -5を入れた実行結果
rb:10:in `type': 年齢がマイナスです！ (RuntimeError)
	from chap111.rb:25:in `<main>'
~~~
***

# ensure
例外の有無に関わらず行う処理。

## 例: 年齢で成年、未成年を判定するメソッド(ensureあり)
~~~
def type(age)
	begin
		if age < 0
			raise "年齢がマイナスです！"
		elsif age < 20
			"未成年"
		else
			"成年"
		end
	ensure
			puts "ご利用ありがとうございました"
	end
end

type = type(-5)
puts "#{age}歳は#{type}です。"

# -5を入れた実行結果
rb:10:in `type': 年齢がマイナスです！ (RuntimeError)
	from chap111.rb:25:in `<main>'
ご利用ありがとうございました
~~~
***

# ⭐️ begin~end内に書くべきか
rescue raise ensureは基本的に begin...endブロック内に書くが、	
メソッドの中であれば begin~endなしで直接書くこともある。
***
