# 例外オブジェクトから情報を読む
rubyでは例外もオブジェクトになっている。  
そのためメソッドを呼び出すことで、発生した例外に対する情報を取得できる。
~~~
begin
  1 / 0
rescue => e
  puts "エラークラス => #{e.class}"
  puts "エラーメッセージ => #{e.message}"
  
  puts "バックトレース -------------"
  puts e.backtrace
  puts "--------------------------"
end


【実行結果】
エラークラス => ZeroDivisionError
エラーメッセージ => divided by 0
バックトレース -------------
chery_9.rb:33:in `/'
chery_9.rb:33:in `<main>'
--------------------------
~~~
[メソッドについて詳細](https://github.com/Tarara33/TIL/blob/main/Ruby/%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89/%E5%8D%98%E4%BD%93/message%E3%83%BBbacktrace%E3%83%BBfull_message.md)
***
